
version: "3.8"

services:
  db:
    image: postgres
    restart: always
    container_name: dbTodo

    environment:
      POSTGRES_USER: caleb
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: test

    ports:
      - "5432:5432"

