
version: "3.1"

services:
  db:
    image: postgres
    restart: always
    container_name: dbTodo

    environment:
      POSTGRES_USER: caleb
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: test

    ports:
      - "5431:5431"
   

